---
apiVersion: v1
kind: Service
metadata:
  name: luxxy-covid-testing-system
spec:
  ports:
  - port: 8000
  selector:
    app: luxxy-covid-testing-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxxy-covid-testing-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luxxy-covid-testing-system
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: luxxy-covid-testing-system
    spec:
      containers:
      - name: luxxy-covid-testing-system
        image: ${CONTAINER_LUXXY_COVID_NAME}
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: luxxy-covid-config
---
apiVersion: v1
kind: Service
metadata:
  name: luxxy-covid-testing-system
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: luxxy-covid-testing-system